services:
  postgres_master:
    image: postgres:16.3
    container_name: postgres_mit
    hostname: "primary.postgresql.college-web"
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgresuser"
      POSTGRES_PASSWORD: "postgrespass"
      POSTGRES_DB: "college-web-db"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5455:5432

